// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAs8ZNkuKEjyPBhGq9P0MLL0nAxg4VVOR0',
    appId: '1:398146065972:web:af38db48ef0febbea3dc61',
    messagingSenderId: '398146065972',
    projectId: 'discover-travel-app',
    authDomain: 'discover-travel-app.firebaseapp.com',
    storageBucket: 'discover-travel-app.appspot.com',
    measurementId: 'G-15GSQGBSXX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjeTLQcxnT2ne33K1oENA87zpB6NRWO5A',
    appId: '1:398146065972:android:ab761ffb963b4f20a3dc61',
    messagingSenderId: '398146065972',
    projectId: 'discover-travel-app',
    storageBucket: 'discover-travel-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVI5huPRSLUKxE_9Ib-0VRZ1yMgkQ7FiM',
    appId: '1:398146065972:ios:a7361b849500e224a3dc61',
    messagingSenderId: '398146065972',
    projectId: 'discover-travel-app',
    storageBucket: 'discover-travel-app.appspot.com',
    androidClientId: '398146065972-q3nqrf0akr492tm8ivddo19893pgpfj5.apps.googleusercontent.com',
    iosClientId: '398146065972-m9js9kilpnmd4vdquma9b4k9s19k2brs.apps.googleusercontent.com',
    iosBundleId: 'com.example.discover',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVI5huPRSLUKxE_9Ib-0VRZ1yMgkQ7FiM',
    appId: '1:398146065972:ios:d6f1554ea24a3449a3dc61',
    messagingSenderId: '398146065972',
    projectId: 'discover-travel-app',
    storageBucket: 'discover-travel-app.appspot.com',
    androidClientId: '398146065972-q3nqrf0akr492tm8ivddo19893pgpfj5.apps.googleusercontent.com',
    iosClientId: '398146065972-r235emq7408143ud7b72gj6e2abptj5b.apps.googleusercontent.com',
    iosBundleId: 'com.example.discover.RunnerTests',
  );
}
